---
- name: web application deploy
  hosts: west
  remote_user: hank
  vars:
    homedir: "/home/{{ user }}"
    org: aliencyborg
    repo: homepage
    user: hank
    workdir: "{{ homedir }}/code/src/github.com/{{ org }}/{{ repo }}"
  tasks:
    - name: ensure workdir parent dir is present
      file:
        path: "{{ homedir }}/code/src/github.com/{{ org }}"
        state: directory
      tags: [ prod, stage ]

    ## STAGE ##

    - name: clone or update repo (stage)
      git:
        dest: "{{ workdir }}"
        repo: "https://github.com/{{ org }}/{{ repo }}.git"
        update: yes
        version: stage
      tags: stage

    - name: build docker image (stage)
      docker_image:
        force_source: yes
        name: aliencyborg-web
        source: build
        tag: stage
        build:
          path: "{{ workdir }}"
          pull: no
      tags: stage

    - name: run docker container (stage)
      docker_container:
        expose: 80
        image: aliencyborg-web:stage
        name: aliencyborg-stage-web
        restart_policy: always
        env:
          HSTS: 'off'
          LETSENCRYPT_HOST: 'stage.aliencyb.org'
          PORT: '80'
          VIRTUAL_HOST: 'stage.aliencyb.org'
      tags: stage

    ## PRODUCTION ##

    - name: clone or update repo (prod)
      git:
        dest: "{{ workdir }}"
        repo: "https://github.com/{{ org }}/{{ repo }}.git"
        update: yes
        version: prod
      tags: prod

    - name: build docker image (prod)
      docker_image:
        force_source: yes
        name: aliencyborg-web
        source: build
        tag: prod
        build:
          path: "{{ workdir }}"
          pull: no
      tags: prod

    - name: run docker container (prod)
      docker_container:
        expose: 80
        image: aliencyborg-web:prod
        name: aliencyborg-web
        restart_policy: always
        env:
          HSTS: 'off'
          LETSENCRYPT_HOST: 'aliencyb.org,www.aliencyb.org'
          PORT: '80'
          VIRTUAL_HOST: 'aliencyb.org,www.aliencyb.org'
      tags: prod

